version: '3.3'


services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "db-migrate up && npm start"
    environment:
      - NODE_ENV=development